#ifndef VITAWAVE_APP_PATHS_H
#define VITAWAVE_APP_PATHS_H

#define VITAWAVE_DATA_DIR "ux0:data/VitaWave"
#define VITAWAVE_NETWORK_DIR VITAWAVE_DATA_DIR "/network"
#define VITAWAVE_KNOWN_HOSTS_PATH VITAWAVE_NETWORK_DIR "/known_hosts"
#define VITAWAVE_NETWORK_PASSWORDS_PATH VITAWAVE_NETWORK_DIR "/passwords.txt"
#define VITAWAVE_SESSION_LOG_PATH VITAWAVE_DATA_DIR "/session_log.txt"

#endif
