#ifndef VITAMEDIADECK_APP_PATHS_H
#define VITAMEDIADECK_APP_PATHS_H

#define VITAMEDIADECK_DATA_DIR "ux0:data/VitaMediaDeck"
#define VITAMEDIADECK_NETWORK_DIR VITAMEDIADECK_DATA_DIR "/network"
#define VITAMEDIADECK_KNOWN_HOSTS_PATH VITAMEDIADECK_NETWORK_DIR "/known_hosts"
#define VITAMEDIADECK_NETWORK_PASSWORDS_PATH VITAMEDIADECK_NETWORK_DIR "/passwords.txt"
#define VITAMEDIADECK_SESSION_LOG_PATH VITAMEDIADECK_DATA_DIR "/session_log.txt"

#endif
